[project]
name = "wikidata-rdf-patch"
version = "0.1.1"
description = "Edit Wikidata items with RDF"
readme = "README.md"
authors = [{ name = "Joshua Peek" }]
requires-python = ">=3.12"
dependencies = [
    "click>=8.0.0,<9.0",
    "rdflib>=7.0.0,<8.0",
    "tqdm>=4.60.0,<5.0",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Typing :: Typed",
]

[project.entry-points.console_scripts]
wikidata-rdf-patch = "wikidata_rdf_patch.cli:main"

[project.optional-dependencies]
dev = [
    "mypy>=1.0.0,<2.0",
    "pytest>=8.0.0,<9.0",
    "ruff>=0.4.0",
    "types-tqdm>=4.60.0,<5.0",
]

[tool.ruff.lint]
extend-select = ["I", "UP"]

[tool.mypy]
strict = true
