name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install dependencies
        run: uv sync

      - name: Build package
        run: uv run python -m build

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: dist
          path: dist/*

  test:
    runs-on: ubuntu-slim

    strategy:
      matrix:
        python-version: ["3.12"]
        uv_resolution: ["highest", "lowest-direct"]

    env:
      UV_RESOLUTION: ${{ matrix.uv_resolution }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install dependencies
        run: uv sync

      - name: Test
        run: uv run pytest
